// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4kCPYO7dNdHnAD8rnvaSygdA6s7D7S40',
    appId: '1:30751445300:web:89ba552b1ce90e5a615561',
    messagingSenderId: '30751445300',
    projectId: 'flutterquiz-41964',
    authDomain: 'flutterquiz-41964.firebaseapp.com',
    databaseURL: 'https://flutterquiz-41964.firebaseio.com',
    storageBucket: 'flutterquiz-41964.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGNTqqel3jhCilOE7dG-0njye4ZcxXoGE',
    appId: '1:30751445300:android:60289962a72a0dcb615561',
    messagingSenderId: '30751445300',
    projectId: 'flutterquiz-41964',
    databaseURL: 'https://flutterquiz-41964.firebaseio.com',
    storageBucket: 'flutterquiz-41964.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSpnMM4PEiEDIEJvkYTF9NvaRnUY0AatM',
    appId: '1:30751445300:ios:73c88283b1a180a4615561',
    messagingSenderId: '30751445300',
    projectId: 'flutterquiz-41964',
    databaseURL: 'https://flutterquiz-41964.firebaseio.com',
    storageBucket: 'flutterquiz-41964.appspot.com',
    iosClientId:
        '30751445300-9itifvgftdfan4lsvg44ia9pmsok1vlu.apps.googleusercontent.com',
    iosBundleId: 'com.codeify.flutterFireOdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSpnMM4PEiEDIEJvkYTF9NvaRnUY0AatM',
    appId: '1:30751445300:ios:73c88283b1a180a4615561',
    messagingSenderId: '30751445300',
    projectId: 'flutterquiz-41964',
    databaseURL: 'https://flutterquiz-41964.firebaseio.com',
    storageBucket: 'flutterquiz-41964.appspot.com',
    iosClientId:
        '30751445300-9itifvgftdfan4lsvg44ia9pmsok1vlu.apps.googleusercontent.com',
    iosBundleId: 'com.codeify.flutterFireOdm',
  );
}
